### PR TITLE
Use Django auto_now for created and updated at

### LINKED ISSUE #3: Created_at se dělá pomocí auto_now_add
Created_at a updated není potřeba řešit pomocí modifikace metody save, stačí tam přidat parametr auto_now_add a auto_now: https://docs.djangoproject.com/en/1.10/ref/models/fields/#django.db.models.DateField

### PR DESCRIPTION
**Pull request by just-paja**
Fixes #3

### CODE REVIEW

**Comment by just-paja** [comment]
@PetrDlouhy, I regenerated the initial migration.

**Comment by PetrDlouhy** [comment]
@just-paja That is right. Just please remove the line `# Generated by Django 1.10.4 on 2016-12-26 18:42` from commit to make merging easier.

**Comment by PetrDlouhy** [comment]
@just-paja I meant removing that change, but maybe it is not a big deal.

**Comment by just-paja** [comment]
@PetrDlouhy, removed the message change.

**Pull request merged**
